name: phasefieldx-env
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx==0.10.0
  - scifem
  - mpi4py
  - numpy
  - pandas
  - pyvista
  - python=3.10
  - pytest
  - pip 
  - pip:
      - -r requirements.txt