name: phasefieldx-docs-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyvista
  - scifem
  - jupyterlab
  - numpy
  - vtk
  - scooby>=0.5.1
  - fenics-dolfinx==0.10.0
  - meshio
  - matplotlib
  - imageio>=2.5.0
  - imageio-ffmpeg
  - colorcet
  - cmocean
  - tqdm
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - hypothesis>=5.8.0
  - pip
  - trimesh
  - rtree
  - pyembree
  - pooch
  - trame
  - trame-vuetify
  - trame-vtk
  - typing-extensions
  - pip:
      - pytest-memprof
      - -r requirements.txt
      - -e ..